name: greenstudio-web deploy

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    name: Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Node
        uses: volta-cli/action@v4
        with:
          node-version-file: 'package.json'
          cache: yarn

      - name: Cache Dependency
        uses: actions/cache@v4
        id: cache_dependency
        with:
          path: './.pnp.cjs'
          key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock') }}

      - name: Install Dependency
        if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: Lint
        if: ${{ !env.ACT }}
        run: |
          yarn run lint
          yarn run typecheck

      - name: Build
        if: ${{ !env.ACT }}
        run: |
          yarn run build
        env:
          VITE_CONTACT_URL: ${{ vars.VITE_CONTACT_URL }}
          VITE_RECAPTCHA_SITE_KEY: ${{ vars.VITE_RECAPTCHA_SITE_KEY }}

      - name: Upload Files
        run: |
          which lftp || sudo apt-get update -y && sudo apt-get install lftp -y
          sh ./.github/upload.sh
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          FTP_UPLOAD_DIRECTORY: ${{ secrets.FTP_UPLOAD_DIRECTORY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
