name: greenstudio-web deploy

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    name: Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Node
        uses: volta-cli/action@v4
        with:
          package-json-path: 'package.json'

      - name: Get yarn cache directory path
        id: yarn-cache-path
        run: echo "cache=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache Dependency
        uses: actions/cache@v4
        id: cache_dependency
        with:
          path: ${{ steps.yarn-cache-path.outputs.cache }}
          key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock') }}

      - name: Install Dependency
        run: yarn install --immutable

      - name: Lint
        run: |
          yarn run lint
          yarn run typecheck

      - name: Build
        run: |
          yarn run build
          cat <<EOF > ./build/htaccess
          SetEnv RECAPTCHA_SECRET_KEY ${{ secrets.RECAPTCHA_SECRET_KEY }}
          EOF
        env:
          VITE_CONTACT_URL: ${{ vars.VITE_CONTACT_URL }}
          VITE_RECAPTCHA_SITE_KEY: ${{ vars.VITE_RECAPTCHA_SITE_KEY }}
          VITE_GA_TRACKING_ID: ${{ vars.VITE_GA_TRACKING_ID }}

      - name: Upload Files
        uses: pontago/lftp-deploy-action@master
        with:
          debug: true
          dry_run: true
          protocol: sftp
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_dir: ./build/client/
          remote_dir: ${{ secrets.FTP_UPLOAD_DIRECTORY }}
          script: |
            cd ${{ secrets.FTP_UPLOAD_DIRECTORY }}
            mkdir -p -f php
            put ./backend/app/contact.php -o php/
            chmod 600 php/contact.php
            put ./build/htaccess -o php/.htaccess
            chmod 600 php/.htaccess
